version: '3'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'test123!'
    ports:
      - 1433:1433


# https://collabnix.com/how-to-run-microsoft-sql-in-minutes-using-docker-desktop/
